language: elixir

elixir: 1.5
otp_release: 20.0

notifications:
  email:
    on_success: never
    on_failure: never

addons:
  postgresql: "9.6"

cache:
  directories:
    - _build
    - deps

env:
  global:
    - MIX_ENV=test

matrix:
  include:
    - elixir: 1.4
      otp_release: 20.0
  # allow_failures:
  #   - elixir: 1.3
  #     otp_release: 19.3

before_install:
  - cp .envrc.travis .envrc
  - source .envrc
  - mix local.rebar --force

before_script:
  - mix do ecto.create, ecto.migrate
